# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

variables:
  system.debug: true
  projectName: 'swallow'

stages:
  - stage: Build
    jobs:
      - job: build_job
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          resourceGroupName: $[join($(projectName), $(Build.BuildNumber))]
          location: 'Japan East'
        steps:
        - script: echo 'Hello world!'
