# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - develop

variables:
  projectNamePrefix: 'swallow'

stages:
- stage: Build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    variables:
      location: 'Japan East'
    steps:
    - powershell: |
        $PROJECT_NAME="$env:PROJECT_NAME_PREFIX-$env:BRANCH_NAME-ci"
        echo "##vso[task.setvariable variable=ProjectName]$PROJECT_NAME"
      env:
        PROJECT_NAME_PREFIX: $(projectNamePrefix)
        BRANCH_NAME: $(Build.SourceBranchName)
      displayName: 'Set ProjectName'

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Connected Azure Subscription'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(ProjectName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: azuredeploy.json
        csmParametersFile: parameters.minimum.json
        overrideParameters: '-projectName $(ProjectName)'
        deploymentMode: 'Incremental'
        deploymentOutputs: DeployOutput

    - powershell: |
        $DeployOutput=$env:DeployOutput | ConvertFrom-Json
        $RESOURCE_GROUP_NAME=$DeployOutput.resourceGroupName.value
        $FUNCTIONS_NAME=$DeployOutput.functionName.value
        echo "##vso[task.setvariable variable=RESOURCE_GROUP_NAME]$RESOURCE_GROUP_NAME"
        echo "##vso[task.setvariable variable=FUNCTIONS_NAME]$FUNCTIONS_NAME"
      displayName: 'Set variables (RESOURCE_GROUP_NAME, FUNCTIONS_NAME)'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/functions'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'Connected Azure Subscription'
        appType: 'functionApp'
        appName: $(FUNCTIONS_NAME)
        package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        deploymentMethod: 'runFromPackage'

    - task: UseNode@1
      inputs:
        version: 10.x

    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'Connected Azure Subscription'
        ScriptType: 'InlineScript'
        Inline: |
          $CRED = Get-AzureRMWebAppPublishingProfile -ResourceGroupName $env:RESOURCE_GROUP_NAME -Name $env:FUNCTIONS_NAME -Format "MSDeploy" | ConvertFrom-Json
          echo "##vso[task.setvariable variable=PUBLISHING_USER_NAME]$CRED.userName"
          echo "##vso[task.setvariable variable=PUBLISHING_PASSWORD]$CRED.userPWD"
      displayName: 'Set variables (PUBLISHING_USER_NAME, PUBLISHING_PASSWORD)'

    - powershell: |
        echo $env:PUBLISHING_USER_NAME
        echo $env:PUBLISHING_PASSWORD

    - powershell: |
        cd tests
        npm install
        npm run test
      displayName: 'Run test'