# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - develop

variables:
  projectNamePrefix: 'swallow'

stages:
- stage: Build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    variables:
      location: 'Japan East'
    steps:
    - powershell: |
        $PROJECT_NAME="$env:PROJECT_NAME_PREFIX-$env:BRANCH_NAME-ci"
        echo "##vso[task.setvariable variable=ProjectName]$PROJECT_NAME"
      env:
        PROJECT_NAME_PREFIX: $(projectNamePrefix)
        BRANCH_NAME: $(Build.SourceBranchName)
      displayName: 'Set ProjectName'

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Connected Azure Subscription'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(ProjectName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: azuredeploy.json
        csmParametersFile: parameters.minimum.json
        overrideParameters: '-projectName $(ProjectName)'
        deploymentMode: 'Incremental'
        deploymentOutputs: DeployOutput

    - powershell: |
        $DeployOutput=$env:DeployOutput | ConvertFrom-Json
        $SUBSCRIPTION_ID=$DeployOutput.subscriptionId.value
        $RESOURCE_GROUP_NAME=$DeployOutput.resourceGroupName.value
        $FUNCTION_NAME=$DeployOutput.functionName.value
        echo "##vso[task.setvariable variable=SUBSCRIPTION_ID]$SUBSCRIPTION_ID"
        echo "##vso[task.setvariable variable=RESOURCE_GROUP_NAME]$RESOURCE_GROUP_NAME"
        echo "##vso[task.setvariable variable=FUNCTION_NAME]$FUNCTION_NAME"
      displayName: 'Set variables (SUBSCRIPTION_ID, RESOURCE_GROUP_NAME, FUNCTION_NAME)'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/functions'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'Connected Azure Subscription'
        appType: 'functionApp'
        appName: $(FUNCTION_NAME)
        package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        deploymentMethod: 'runFromPackage'

    - task: UseNode@1
      inputs:
        version: 10.x

    - powershell: |
        cd tests
        npm install
        npm run test
