# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - develop

variables:
  projectNamePrefix: 'swallow'

stages:
- stage: Build
  jobs:
  - job: build_job
    pool:
      vmImage: 'windows-latest'
    variables:
      location: 'Japan East'
    steps:
    - script: |
        echo '##vso[task.setvariable variable=ProjectName]$(projectNamePrefix)-$(Build.SourceBranchName)-ci'
      displayName: 'Set ProjectName'

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Connected Azure Subscription'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(ProjectName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: azuredeploy.json
        csmParametersFile: parameters.minimum.json
        overrideParameters: '-projectName $(ProjectName)'
        deploymentMode: 'Incremental'
        deploymentOutputs: DeployOutput

    - powershell: |
        echo $env:DeployOutput
        $DeployOutput=$env:DeployOutput | ConvertFrom-Json
        echo $DeployOutput
        $SUBSCRIPTION_ID=$DeployOutput.subscriptionId.value
        echo $SUBSCRIPTION_ID
        $RESOURCE_GROUP_NAME=$DeployOutput.resourceGroupName.value
        echo $RESOURCE_GROUP_NAME
        $FUNCTION_NAME=$DeployOutput.functionName.value
        echo $FUNCTION_NAME
        echo '##vso[task.setvariable variable=SUBSCRIPTION_ID]$SUBSCRIPTION_ID'
        echo '##vso[task.setvariable variable=RESOURCE_GROUP_NAME]'$(echo $RESOURCE_GROUP_NAME)
        echo "##vso[task.setvariable variable=FUNCTION_NAME]$FUNCTION_NAME"

    - script: |
        echo $SUBSCRIPTION_ID
        echo $RESOURCE_GROUP_NAME
        echo $FUNCTION_NAME
